### ISSUE TITLE
Improve dialog-box message when software module is locked by another of its own instance

### ISSUE THREAD

**Issue by badshah400** [yast/yast-yast2#1102]
When one YaST SW module window is open, opening another one produces a "Accessing the Software Management Failed" (btw it should probably say "Accessing the Software Management Module Failed") but only provides a cryptic explanation of which other process is locking it, saying "System management is locked by the application with pid 9999 (/usr/bin/ruby.ruby2.7)."

It would help non-technical users a lot if it just reminded them that there is another YaST2 SW module open and either to use that or close that. Even a hint like "Perhaps you have another SW module window open?" when the matched PID refers to rubyX.Y would be quite helpful from the current status quo. Users, esp. someone just starting with openSUSE, are not expected to know that ruby is the command line driving YaST2 processes, are they?

![Screenshot from 2020-09-23 16-38-38](https://user-images.githubusercontent.com/3532467/94027627-55e4ef80-fdbb-11ea-9643-8106ede44c60.png)

**Comment by lslezak** [comment]
YaST just displays the header and the question in the dialog (see [here](https://github.com/yast/yast-yast2/blob/66bc64d08c6ff017b88e3cff63fd02d78bbcf7f1/library/packages/src/modules/PackageLock.rb#L179-L183)).

The main part of the error message comes directly from the underlying libzypp library ([here](https://github.com/openSUSE/libzypp/blob/4c6904a431c7e194f6a612a467869f11523a6053/zypp/ZYppFactory.cc#L398-L399)). 

We can only add a hint into the popup.

![pkg_lock](https://user-images.githubusercontent.com/907998/97967225-3a5b0480-1dbd-11eb-973c-96298cb6eb9d.png)

**Comment by lslezak** [comment]
Fixed in https://github.com/yast/yast-pkg-bindings/pull/146
