### ISSUE TITLE
Adding a public key results in KIO worker message

### ISSUE THREAD

**Issue by beritter** [yast/yast-yast2#1290]
I've tried to add a public key to my user account. I noticed a KIO worker warning when I clicked  "hinzufügen" ("add") on the ssh-keys tab in the user module.

The error message: "Unable to create KIO worker. Can not create a socket for launching a KIO worker for protocol 'tags'"

Also I noticed that there is no way to get into a hidden directory. CTRL+L also does not work to get a manual input for the directory.

This is openSUSE Tumbleweed 20230304

![image](https://user-images.githubusercontent.com/128027208/228782823-6dd8ef45-8113-4274-a631-e55959f00cb1.png)

**Comment by shundhammer** [comment]
This is not at all YaST related.
