### ISSUE TITLE
New Hardware Detection Library

### ISSUE THREAD

**Issue by kobliha** [yast/yast-yast2#135]
- There are several places in Yast where code behaves dependently on the detected hardware, especially hardware vendor
- For instance, grep all the code for `dell` or `sgi`
- This functionality deserves a decent library

**Comment by dgdavid** [comment]
@kobliha, what do you think now about it? Do we have the hardware detection library? If not, is it worth to keep this issue open?

**Comment by kobliha** [comment]
We already have something similar, we even grep for DELL for some cases :D Hey, this was 2013!!!
