### ISSUE TITLE
remove unused storing config in subversion

### ISSUE THREAD

**Issue by jreidinger** [yast/yast-yast2#410]
https://github.com/yast/yast-yast2/blob/master/library/general/src/fillup/sysconfig.yast2#L42 it was dropped as snapper is preffered way, so also remove entries from sysconfig

**Comment by lslezak** [comment]
Some details: the only place in YaST which used `STORE_CONFIG_IN_SUBVERSION` + `SUBVERSION_ADD_DIRS_RECURSIVE` was removed in https://github.com/yast/yast-yast2/commit/71a9b8b66a747f34aea767229cb7aa757f0e2d46#diff-2378a1aff0b9fd66f14a65b5fcfda9b9L81

**Comment by dgdavid** [comment]
@jreidinger, @lslezak friendly ping ;)

**Comment by shundhammer** [comment]
This looks very outdated. IMHO we can safely close it.

**Comment by lslezak** [comment]
OK, closing...
