### ISSUE TITLE
[Feature request] yast-btrfs-maintanance module

### ISSUE THREAD

**Issue by MikhailKasimov** [yast/yast-yast2#424]
Don't know does anybody read features.opensuse.org , will try to put feature request here, because it seems to be a good idea to have a general yast module, which join different aspects of btrfs-maintanance itself, instead of yast2-snapper, which has narrow functionality by design. First conception: https://features.opensuse.org/319717

**Comment by shundhammer** [comment]
Yes, please use that mailing list.
