### ISSUE TITLE
Allow to abort on Check() in PackageLock.rb

### ISSUE THREAD

**Issue by marguerite** [yast/yast-yast2#477]
<pre>
Index: modules/PackageLock.rb
===================================================================
---a/PackageLock.rb
++++b/PackageLock.rb
@@ -115,6 +115,7 @@ module Yast
             ),
             Label.ContinueButton,
             Label.RetryButton,
+           Label.AbortButton,
             # 'Continue' instead of 'Retry'
             :focus_yes
           ) == false
</pre>

I just wonder why we have AbortButton in Connect() function while not in Check() function?

Here's when Check() is used (just one of the situations):

"Software Management is locked by pid (...packagekitd)...
Continue, Retry?"

I didn't see any special point that we need to block users from aborting YaST in this case...
Because the update applet is doing something, the safest operation should be "Abort".

Can anyone explain the design please?

Marguerite

**Comment by lslezak** [comment]
Um, there is actually also [Connect](https://github.com/yast/yast-yast2/blob/145c7821e654996cf17118a866bc7740537183fc/library/packages/src/modules/PackageLock.rb#L135) function which can show the *Abort* button, maybe we should just switch to it...

**Comment by dgdavid** [comment]
I guess this is no longer relevant. It's from 2016 and there is no response.

So, let's me close it.

Sorry for the inconvenience.
