### ISSUE TITLE
Help from two nested CWM::ReplacePoints do not work

### ISSUE THREAD

**Issue by jreidinger** [yast/yast-yast2#585]
Basically problem is that CWM have static help. It can be replaced for single widget by special call. But that widget is also dynamically add it won't work. Proposed solution is to allow to have help as dynamic method ( which will be used by replace point ) and this special call then reevaluate such calls.

**Comment by dgdavid** [comment]
I think this in no longer relevant. What do you think, @jreidinger?

**Comment by jreidinger** [comment]
yes, fixed with https://github.com/yast/yast-yast2/commit/fd7a4b9e3dadaa615700ea698aa7db1f3115e112#diff-11bba21261a62f97486f3dfe8701b2cb
