### ISSUE TITLE
one offline repository prevents installation of software

### ISSUE THREAD

**Issue by smithfarm** [yast/yast-yast2#612]
Ulrich Windl writes in https://bugzilla.opensuse.org/show_bug.cgi?id=739487:

If you have configured a repository on an USB-Stick, that repository will be unavailable when the stick is not there; that's logical. What's not logical is that package management first tries to refresh (from) such an offline repository. Even if you manually select not to refresh that repository, and mnaually say to skip that repository, software management is unable to install software.
for example, when using totem to view a ".m2t" file, additional packages are needed. That installation (via "apper") however fails for the reasons explained above. Unless the application is restarted, installation is not re-tried.
Manual work-around is to temporarily disable the USB-stick repository, then restart the application.

Software management should be smart enough to skip unreachable repositories.

Reproducible: Always

Steps to Reproduce:
1. Configure some repository on a USB stick. Unplug that stick afterwards.
2. Use some application that needs additional software packages
Actual Results:  
Additional packages cannot be installed, even if the required repositories are online.

Expected Results:  
Additional packages from unaffected repositories should be installed.

This bug also existed in older versions of openSUSE

**Comment by shundhammer** [comment]
Please use Bugzilla for this.

**Comment by smithfarm** [comment]
@shundhammer There's already a bugzilla https://bugzilla.opensuse.org/show_bug.cgi?id=739487 but it was against a product (openSUSE 12.1) that has been EOLed. 

Feel free to reopen the bug, then, and change the product.
