### ISSUE TITLE
Broken link to bugzilla

### ISSUE THREAD

**Issue by binary-sequence** [yast/yast-yast2#682]
In this file: https://github.com/yast/yast-yast2/blob/master/CONTRIBUTING.md

The link to bugzilla doesn't work. Please, find screenshot attached.

![bugzilla_factory_does_not_exist](https://user-images.githubusercontent.com/2727538/35562621-3b827ccc-05b4-11e8-88fe-fc00498aaa0e.jpg)

**Comment by binary-sequence** [comment]
@SergioAtSUSE

**Comment by lslezak** [comment]
The correct product is now `openSUSE Tumbleweed` (instead of `openSUSE Factory`), the tricky part is that this URL is used in *all* YaST Git repositories. That means ~120 places... :worried:

**Comment by dgdavid** [comment]
It's true that updating the link means to update ~127 places... but we should do it.

Anyway, I'm going to propose having a single `CONTRIBUTING.md` (this one) and use a link to it in the other repos. From that change on, we'll need to update the content once.

What do you think? Any other idea?

**Comment by jreidinger** [comment]
@dgdavid link won't work. As CONTRIBUTING.md is file that is shown when people create pull request. So decision was to have it multiple times, but identical. With mass deploying it should be possible to do it. You just need to unprotect master, commit to master and protect it again. @lslezak knows details.

**Comment by dgdavid** [comment]
Thanks @jreidinger 

I forget to mentions here that I also [started the discussion in the yast-devel mailing list](https://lists.opensuse.org/yast-devel/2020-02/msg00006.html) and there is [another proposal](https://lists.opensuse.org/yast-devel/2020-02/msg00007.html) that looks better: [creating a default community health file](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file).

Let's see.

**Comment by lslezak** [comment]
JFYI: I have created the https://github.com/yast/.github repository containing the CONTRIBUTION.md file.

**Comment by dgdavid** [comment]
Finally, we [deleted all `CONTRIBUTING.md` files](https://github.com/pulls?q=user%3Ayast+%22Delete+CONTRIBUTING.md%22+is%3Apr) from the YaST packages.

The good and updated one is available at https://github.com/yast/.github/blob/master/CONTRIBUTING.md, as part of our [default community health files](https://lists.opensuse.org/yast-devel/2020-03/msg00004.html).

Thanks.
