### ISSUE TITLE
Better icon theme support

### ISSUE THREAD

**Issue by hellcp** [yast/yast-yast2#689]
YaST doesn't have support for external icon themes without making changes to links inside theme directory. Data inside of library/general/src/modules/Directory.rb in case of Wizard themes always has higher priority over system theme. In case of icons, removing icon symlink doesn't have effect on icon theme and falls back to hicolor, as opposed to system theme which affects YaST when there is no theme with higher priority in /usr/share/YaST2/theme/current/wizard directory.

Icon module in library/general/src/modules/Icon.rb doesn't take any other option than .png into account (it's not the only lib that does that). It would be nice to at least have additional support for SVG, even though it's optional in [freedesktop standard](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#definitions) (but I don't see you supporting .xpm, so at least support .svg which is at least somewhat popular on desktop).

I couldn't find mentions about pattern icons and package groups icons in software manager, but those don't even want to change with icon theme symlink (/usr/share/YaST2/theme/current/icons) changed to something different. It would be awesome if those followed the same spec. For now from users point of view they seem to be hardcoded and impossible to be changed to anything different.

**Comment by lslezak** [comment]
JFYI: this is the list of pulls:

- [x] https://github.com/yast/yast-yast2/pull/868
- [x] https://github.com/yast/yast-theme/pull/100
- [x] https://github.com/yast/yast-add-on/pull/67
- [ ] https://github.com/yast/yast-alternatives/pull/41
- [ ] https://github.com/yast/yast-audit-laf/pull/18
- [ ] https://github.com/yast/yast-auth-client/pull/67
- [ ] https://github.com/yast/yast-auth-server/pull/47
- [ ] https://github.com/yast/yast-autoinstallation/pull/479
- [ ] https://github.com/yast/yast-bootloader/pull/545
- [ ] https://github.com/yast/yast-boot-server/pull/11
- [ ] https://github.com/yast/yast-cio/pull/29
- [ ] https://github.com/yast/yast-cluster/pull/43
- [ ] https://github.com/yast/yast-control-center/pull/33
- [ ] https://github.com/yast/yast-country/pull/201
- [ ] https://github.com/yast/yast-dhcp-server/pull/40
- [ ] https://github.com/yast/yast-dns-server/pull/78
- [ ] https://github.com/yast/yast-docker/pull/24
- [ ] https://github.com/yast/yast-drbd/pull/20
- [ ] https://github.com/yast/yast-fcoe-client/pull/53
- [ ] https://github.com/yast/yast-firewall/pull/106
- [ ] https://github.com/yast/yast-firstboot/pull/56
- [ ] https://github.com/yast/yast-fonts/pull/41
- [ ] https://github.com/yast/yast-ftp-server/pull/53
- [ ] https://github.com/yast/yast-geo-cluster/pull/22
- [ ] https://github.com/yast/yast-http-server/pull/36
- [ ] https://github.com/yast/yast-installation/pull/765
- [ ] https://github.com/yast/yast-instserver/pull/34
- [ ] https://github.com/yast/yast-iplb/pull/15
- [ ] https://github.com/yast/yast-iscsi-client/pull/76
- [ ] https://github.com/yast/yast-iscsi-lio-server/pull/83
- [ ] https://github.com/yast/yast-isns/pull/21
- [ ] https://github.com/yast/yast-journal/pull/37
- [ ] https://github.com/yast/yast-kdump/pull/101
- [ ] https://github.com/yast/yast-mail/pull/39
- [ ] https://github.com/yast/yast-migration/pull/44
- [ ] https://github.com/yast/yast-multipath/pull/26
- [ ] https://github.com/yast/yast-network/pull/702
- [ ] https://github.com/yast/yast-nfs-client/pull/74
- [ ] https://github.com/yast/yast-nfs-server/pull/30
- [ ] https://github.com/yast/yast-nis-client/pull/38
- [ ] https://github.com/yast/yast-nis-server/pull/15
- [ ] https://github.com/yast/yast-ntp-client/pull/128
- [ ] https://github.com/yast/yast-online-update/pull/25
- [ ] https://github.com/yast/yast-online-update-configuration/pull/17
- [ ] https://github.com/yast/yast-printer/pull/22
- [ ] https://github.com/yast/yast-proxy/pull/22
- [ ] https://github.com/yast/yast-rdp/pull/15
- [ ] https://github.com/yast/yast-rear/pull/14
- [ ] https://github.com/yast/yast-registration/pull/410
- [ ] https://github.com/yast/yast-samba-client/pull/66
- [ ] https://github.com/yast/yast-samba-server/pull/64
- [ ] https://github.com/yast/yast-scanner/pull/20
- [ ] https://github.com/yast/yast-security/pull/49
- [ ] https://github.com/yast/yast-services-manager/pull/181
- [ ] https://github.com/yast/yast-snapper#63
- [ ] https://github.com/yast/yast-sound#29
- [ ] https://github.com/yast/yast-sudo#8
- [ ] https://github.com/yast/yast-support#32
- [ ] https://github.com/yast/yast-sysconfig#24
- [ ] https://github.com/yast/yast-tftp-server#24
- [ ] https://github.com/yast/yast-tune#35
- [ ] https://github.com/yast/yast-update#117
- [ ] https://github.com/yast/yast-users#185
- [ ] https://github.com/yast/yast-vm#37
- [ ] https://github.com/yast/yast-vpn#8
- [ ] https://github.com/yast/yast-squid#22

**Comment by hellcp** [comment]
As addition to that list, preparing for breeze theme:
- [ ] yast/yast-rake/pull/63
- [ ] yast/yast-theme/pull/103

**Comment by noahadvs** [comment]
https://github.com/yast/yast-storage-ng/pull/806
https://github.com/yast/yast-packager/pull/393
https://github.com/yast/yast-slp-server/pull/28

**Comment by lslezak** [comment]
Just for the record, some additional fixes are in 

- [x] https://github.com/yast/skelcd-control-leanos/pull/33
- [x] https://github.com/yast/skelcd-control-openSUSE/pull/157
- [x] https://github.com/yast/skelcd-control-openSUSE/pull/158
- [x] https://github.com/yast/skelcd-control-SLED/pull/88
- [x] https://github.com/yast/skelcd-control-SLES/pull/118
- [x] https://github.com/yast/skelcd-control-Kubic/pull/24
- [x] https://github.com/yast/skelcd-control-CAASP/pull/77
- [x] https://github.com/yast/yast-packager/pull/394
- [x] https://github.com/yast/yast-x11/pull/19

**Comment by noahadvs** [comment]
* [ ] https://github.com/yast/yast-vm/pull/38
* [ ] https://github.com/yast/yast-yast2/pull/869
